print('- ' * 30)
print('Algoritmo de calculo para alugar carros')
print('- ' * 30)

car = input('Digite o carro alugado:')
kms = float(input('Quantos Km foram percorridos?'))
day = int(input('Por Quantos dias o carro foi alugado?'))
dcar = int(60)
kmr = float(0.15)
kms_r = float(kms * kmr)
day_r = int(day * dcar)
total = (kms_r + day_r)

print('- ' * 30)
print('Obrigado por escolher Amogus Locator')
print('- ' * 30)
print('Você escolheou o {} como carro utilizado'.format(car))
print('O total a pagar pela diaria é {:.2}'.format(kms_r))
print('O total a pagar pela Kilometragem do carro é {}'.format(day_r))
print('- ' * 30)
print('Subtotal: {} reais'.format(total))
print('- ' * 30)